apiVersion: v1
kind: Secret
metadata:
  name: docker-auth-for-tekton
  annotations:
    tekton.dev/docker-0: https://index.docker.io
    tekton.dev/docker-1: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>