name: Build & Test

on:
  push:
    paths-ignore:
      - 'docs_template/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs_template/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sysdiglabs/sysdig-inline-scan

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pipenv
      run: pip install pipenv==2018.11.26

    - name: Run shellcheck tests
      run: make shellcheck

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.SYSDIGLABS_DOCKERHUB_USER }}
        password: ${{ secrets.SYSDIGLABS_DOCKERHUB_TOKEN }}
        repository: sysdiglabs/secure-inline-scan
        add_git_labels: true
        dockerfile: Dockerfile
        tags: ci
        push: false

    - name: Run container tests
      run: make unittests

